version: '3.3'

services:
    zoo1:
        image: zk:v1
        restart: always
        hostname: zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zk:v1
        restart: always
        hostname: zoo2
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zk:v1
        restart: always
        hostname: zoo3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

    kafka1:
        image: kafka:v1
        ports:
            - 9092:9092
        environment:
            ISCLUSTER: "true"
            BROKER_ID: 0
            PORT: 9092
            HOST_COMMAND: "ifconfig | sed -n '2p' | cut -d' ' -f10"
            LISTENERS: PLAINTEXT://
            LOG_DIRS: /tmp/kafka/kafka-logs-1
            ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
        volumes:
            - ../volumes/docker.sock1:/var/run/docker.sock
            - ../volumes/kafka-logs-1:/tmp/kafka/kafka-logs-1

    kafka2:
        image: kafka:v1
        ports:
            - 9093:9093
        environment:
            ISCLUSTER: "true"
            BROKER_ID: 1
            PORT: 9093
            HOST_COMMAND: "ifconfig | sed -n '2p' | cut -d' ' -f10"
            LISTENERS: PLAINTEXT://
            LOG_DIRS: /tmp/kafka/kafka-logs-2
            ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
        volumes:
            - ../volumes/docker.sock2:/var/run/docker.sock
            - ../volumes/kafka-logs-2:/tmp/kafka/kafka-logs-2
